name: BarlowHSIC
channels:
  - pytorch
  - conda-forge
dependencies:
  # System
  - pip>=21.2.4
  - tqdm>=4.62.3
  - jupyter>=1.0
  - jupyterlab>=3.2.6
  #
  # Data science
  - pandas>=1.4.0
  #
  # Deep learning
  - pytorch>=1.10.2
  - torchvision>=0.11.3
  #
  # Test
  - pytest>=6.2.5
  - flake8>=3.7.9
  - autopep8>=1.6.0
  - pep8>=1.7.1
  #
  - pip:
    - thop
